### ISSUE TITLE
Name_Update callback does not print correct old custom name

### ISSUE THREAD

**Issue by gizzmo** [Jods-GH/CustomNames#2]
### Description

When changing a custom name, the callback `Name_Update` doesn't print the old custom name.

```
[07:22] Added: Xitnuh-AlteracMountains is now Renamed to First 
[07:22] Edited: Xitnuh-AlteracMountains is now Renamed to Second (was Second) 
[07:22] Edited: Xitnuh-AlteracMountains is now Renamed to Third (was Third)
```

This is due to the following lines changing the DB value before passing that new DB value to the callback. 

https://github.com/Jods-GH/CustomNames/blob/8cf1fb46b11e0cb6d38431d87449d79f8ab4a7ec/API.lua#L131-L132
https://github.com/Jods-GH/CustomNames/blob/8cf1fb46b11e0cb6d38431d87449d79f8ab4a7ec/API.lua#L93-L96

### World of Warcraft Flavor

Retail (Default)

### Reproduction Steps

1. `/cn add Xitnuh-AlteracMountains to First`
2.  `/cn edit Xitnuh-AlteracMountains to Second`
3.  `/cn edit Xitnuh-AlteracMountains to Third`

**Comment by Jodsderechte** [comment]
Thanks! nice catch fixed in next version
